SET(CMAKE_SYSTEM_NAME Linux)
SET(CMAKE_C_COMPILER gcc CACHE INTERNAL "")
SET(CMAKE_CXX_COMPILER g++ CACHE INTERNAL "")

SET(CMAKE_C_FLAGS_DEBUG "")
SET(CMAKE_C_FLAGS_DEBUG "-O0 -g")
SET(CMAKE_CXX_FLAGS_DEBUG "")
SET(CMAKE_CXX_FLAGS_DEBUG "-O0 -g")

SET(CMAKE_C_FLAGS_RELEASE "")
SET(CMAKE_C_FLAGS_RELEASE "-flto -Ofast -DNDEBUG")
SET(CMAKE_CXX_FLAGS_RELEASE "")
SET(CMAKE_CXX_FLAGS_RELEASE "-flto -Ofast -DNDEBUG")
