SET(CMAKE_SYSTEM_NAME Linux)
SET(CMAKE_C_COMPILER gcc CACHE INTERNAL "")
SET(CMAKE_CXX_COMPILER g++ CACHE INTERNAL "")

SET(CMAKE_C_FLAGS_DEBUG "")
SET(CMAKE_C_FLAGS_DEBUG "-O0 -g")
SET(CMAKE_CXX_FLAGS_DEBUG "")
SET(CMAKE_CXX_FLAGS_DEBUG "-O0 -g")

SET(CMAKE_C_FLAGS_RELEASE "")
SET(CMAKE_C_FLAGS_RELEASE "-flto -ffat-lto-objects -Ofast -DNDEBUG")
SET(CMAKE_CXX_FLAGS_RELEASE "")
SET(CMAKE_CXX_FLAGS_RELEASE "-flto -ffat-lto-objects -Ofast -DNDEBUG")
SET(CMAKE_EXE_LINKER_FLAGS_RELEASE_INIT "-flto")
SET(CMAKE_STATIC_LINKER_FLAGS_RELEASE_INIT "-flto")

SET(CMAKE_AR "gcc-ar")
SET(CMAKE_C_ARCHIVE_CREATE "<CMAKE_AR> qcs <TARGET> <LINK_FLAGS> <OBJECTS>")
SET(CMAKE_C_ARCHIVE_FINISH true)
