SET(CMAKE_SYSTEM_NAME Darwin)
SET(LLVM_PATH "/opt/homebrew/Cellar/llvm/13.0.1_1")
SET(CMAKE_C_COMPILER "${LLVM_PATH}/bin/clang" CACHE INTERNAL "")
SET(CMAKE_CXX_COMPILER "${LLVM_PATH}/bin/clang++" CACHE INTERNAL "")

SET(CMAKE_C_FLAGS_DEBUG "")
SET(CMAKE_C_FLAGS_DEBUG "-O0 -g")
SET(CMAKE_CXX_FLAGS_DEBUG "")
SET(CMAKE_CXX_FLAGS_DEBUG "-O0 -g")

SET(CMAKE_C_FLAGS_RELEASE "")
SET(CMAKE_C_FLAGS_RELEASE "-flto -Ofast -ffast-math -DNDEBUG")
SET(CMAKE_CXX_FLAGS_RELEASE "")
SET(CMAKE_CXX_FLAGS_RELEASE "-flto -Ofast -ffast-math -DNDEBUG")

SET(CMAKE_C_CLANG_TIDY "${LLVM_PATH}/bin/clang-tidy")
SET(CMAKE_LINKER "${LLVM_PATH}/bin/ld.lld")
SET(CMAKE_AR "${LLVM_PATH}/bin/llvm-ar" CACHE PATH "AR" FORCE)
SET(CMAKE_RANLIB "${LLVM_PATH}/bin/llvm-ranlib" CACHE PATH "RANLIB" FORCE)
