#include "../include/C2nxt/StdVector.h"

ImplStdVector(char);
ImplStdVector(u8);
ImplStdVector(u16);
ImplStdVector(u32);
ImplStdVector(u64);
ImplStdVector(usize);
ImplStdVector(i8);
ImplStdVector(i16);
ImplStdVector(i32);
ImplStdVector(i64);
ImplStdVector(f32);
ImplStdVector(f64);
ImplStdVector(u8_ptr);
ImplStdVector(u16_ptr);
ImplStdVector(u32_ptr);
ImplStdVector(u64_ptr);
ImplStdVector(usize_ptr);
ImplStdVector(i8_ptr);
ImplStdVector(i16_ptr);
ImplStdVector(i32_ptr);
ImplStdVector(i64_ptr);
ImplStdVector(f32_ptr);
ImplStdVector(f64_ptr);
ImplStdVector(cstring);
ImplStdVector(char_ptr);
ImplStdVector(StdString);
ImplStdVector(StdStringView);
